[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "urm_machine"
version = "0.1.0"
dependencies = [
    "pyinstaller"
]

[tool.setuptools.packages.find]
where = ["src"]
